""""""""""""""""""""""""""""""""""""""""""""""""""
"""Vundle
"""""""""""""""""""""""""""""""""""""""""""""""""""
set nocompatible              " be iMproved, required
filetype off                  " required

let mapleader = "\<Space>" "set leader to space

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" JS / CoffeeScript
Plugin 'pangloss/vim-javascript'
Plugin 'othree/javascript-libraries-syntax.vim'
Plugin 'mxw/vim-jsx'
Plugin 'kchmck/vim-coffee-script'
Plugin 'mtscout6/vim-cjsx'

" other web stuff
Plugin 'othree/html5-syntax.vim'
Plugin 'cakebaker/scss-syntax.vim'

" ruby
Plugin 'tpope/vim-bundler'
Plugin 'vim-ruby/vim-ruby'
Plugin 'tpope/vim-rails'
Plugin 'tpope/vim-rake'

" colorschemes
Plugin 'altercation/vim-colors-solarized' "solarized plugin
Plugin 'chriskempson/base16-vim'

" ui
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

" tmux
Plugin 'edkolev/tmuxline.vim' "makes tmux pretty
Plugin 'sjl/tslime.vim' "send text to a tmux pane
Plugin 'wellle/tmux-complete.vim' "autocomplete with text in tmux buffers

" git
Plugin 'tpope/vim-fugitive' "tpopes git wrapper

" utility
Plugin 'gmarik/Vundle.vim'
Plugin 'tpope/vim-commentary' "gc to toggle comments
Plugin 'tpope/vim-rsi' "gives readline bindings
Plugin 'tpope/vim-sensible'
Plugin 'tpope/vim-speeddating'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-unimpaired' "adds some keybinds?
Plugin 'tpope/vim-vinegar' "makes vim directory browser nicer
Plugin 'terryma/vim-multiple-cursors' "sublime-like cursors

" file opening / search
Plugin 'haya14busa/incsearch.vim' "nice incremental search
Plugin 'kien/ctrlp.vim' "fuzzy search
Plugin 'rking/ag.vim' "wrapper for ag
Plugin 'justinmk/vim-sneak'

" elm
Plugin 'elmcast/elm-vim'

" go
Plugin 'fatih/vim-go'

" rust
Plugin 'rust-lang/rust.vim' "some rust stuff
Plugin 'valloric/youcompleteme' "the best completion ever

" racket / scheme
Plugin 'vim-scripts/paredit.vim' "lisp/racket S-expressions
Plugin 'wlangstroth/vim-racket' "some stuff for racket-lang

" i3
Plugin 'PotatoesMaster/i3-vim-syntax'

" email
Plugin 'guyzmo/notmuch-abook' "get emails out of notmuch db for autocomplete
Plugin 'vim-scripts/lbdbq' "formats mail headers more nicely

" markdown / prose writing
Plugin 'suan/vim-instant-markdown'
Plugin 'reedes/vim-pencil' "soft/hard wraps for txt,md,email
Plugin 'jceb/vim-orgmode'

call vundle#end()
filetype plugin indent on "filetype based indenting 

"""""""""""""""""""""""""""""""""""""""""""""""""""
"""general configuration
"""""""""""""""""""""""""""""""""""""""""""""""""""

augroup myfiletypes
    autocmd! 
    "python first
    autocmd FileType python setlocal tabstop=8
    autocmd FileType python setlocal shiftwidth=4
    autocmd FileType python setlocal expandtab
    autocmd FileType python setlocal softtabstop=4
    autocmd FileType python setlocal autoindent
    autocmd FileType python highlight Excess ctermbg=Green
    autocmd FileType python set nowrap
    autocmd FileType python set nojoinspaces
    "C
    autocmd FileType C set cinoptions=1s
    autocmd FileType C setlocal cindent
    autocmd FileType C setlocal expandtab
    autocmd FileType C setlocal autoindent
    autocmd FileType C set shiftwidth=4
    autocmd FileType C setlocal highlight Excess ctermbg=Green
    autocmd FileType C setlocal match Excess /\%79v.*/
    "ruby
    autocmd FileType ruby setlocal expandtab
    autocmd FileType ruby setlocal autoindent
    autocmd FileType ruby setlocal softtabstop=2
    autocmd FileType ruby setlocal shiftwidth=2
    autocmd FileType ruby setlocal norelativenumber
    " autocmd FileType ruby setlocal nocursorline
    autocmd BufRead,BufNewFile *.arb setfiletype ruby
    "coffeescript
    autocmd FileType coffee setlocal expandtab
    autocmd FileType coffee setlocal autoindent
    autocmd FileType coffee setlocal shiftwidth=2
    autocmd FileType coffee setlocal softtabstop=2
    "html
    autocmd FileType html setlocal expandtab
    autocmd FileType html setlocal autoindent
    autocmd FileType html setlocal shiftwidth=2
    autocmd FileType html setlocal softtabstop=2
    autocmd FileType htmldjango setlocal expandtab
    autocmd FileType htmldjango setlocal autoindent
    autocmd FileType htmldjango setlocal shiftwidth=2
    autocmd FileType htmldjango setlocal softtabstop=2
    autocmd FileType eruby setlocal expandtab
    autocmd FileType eruby setlocal autoindent
    autocmd FileType eruby setlocal shiftwidth=2
    autocmd FileType eruby setlocal softtabstop=2
    "scss
    autocmd FileType scss setlocal expandtab
    autocmd FileType scss setlocal autoindent
    autocmd FileType scss setlocal shiftwidth=2
    autocmd FileType scss setlocal softtabstop=2
    autocmd FileType scss setlocal omnifunc=csscomplete#CompleteCSS
    "elm
    autocmd FileType elm setlocal expandtab
    autocmd FileType elm setlocal autoindent
    autocmd FileType elm setlocal shiftwidth=2
    autocmd FileType elm setlocal softtabstop=2
    "js
    autocmd FileType javascript setlocal omnifunc=tern#Complete
    autocmd FileType javascript setlocal expandtab
    autocmd FileType javascript setlocal autoindent
    autocmd FileType javascript setlocal shiftwidth=2
    autocmd FileType javascript setlocal softtabstop=2
    "org
    autocmd FileType org setlocal foldenable
    autocmd FileType org setlocal nolist
augroup END

"colorscheme
colorscheme solarized
set background=dark
syntax on

"powerline
" let g:Powerline_symbols = 'fancy'

"random options
let ruby_operators=1
let ruby_space_errors=1
let ruby_no_expensive=1
set hidden
set lazyredraw
set number
set wildmenu "better command line completion
set modeline 
set nofoldenable "no goddamn folding
set cursorline "line highlighting
autocmd WinEnter * setlocal cursorline
autocmd WinLeave * setlocal nocursorline
set incsearch
set ignorecase
set smartcase
set hlsearch "highlight searches
set smartindent
set backspace=indent,eol,start
set tabstop=8
set expandtab
set shiftwidth=4
set ruler
set spelllang=en_us "spellcheck is in US english
set grepprg=grep\ -nH\ $*
set laststatus=2
set noshowmode
set ttyfast
set mouse=a
if !has('nvim')
    set ttymouse=sgr
endif
set mousemodel=extend
set noesckeys
set timeout
set timeoutlen=2000
set ttimeoutlen=2000

exec "set listchars=tab:\uBB\uBB,trail:\uB7,nbsp:~"
set list!
" highlight StatusLine ctermfg=blue ctermbg=yellow
if executable('ag')
    set grepprg=ag\ --nogroup\ --nocolor
    let g:ctrlp_user_command = 'ag %s -l --nocolor --hidden -g ""'
    let g:ctrlp_use_caching = 0
    let g:CrtlSpaceglobCommand = 'ag %s -l --nocolor --hidden -g ""'
endif

"" fix the swapfile situation
set noswapfile
set backup
set backupdir=~/.vim/backup//
set undodir=~/.vim/undo//
set cm=blowfish2

"""""""""""""""""""""""""""""""""""""""""""""""""""
"""Plugin Configuration
"""""""""""""""""""""""""""""""""""""""""""""""""""

let g:instant_markdown_slow = 1
let g:sneak#streak = 1
let g:jsx_ext_required = 0 " allow jsx syntax in normal js files
let g:EclimCompletionEngine = 'omnifunc'
let g:ctrlp_extensions = ['buffertag']
let g:incsearch#auto_nohlsearch = 1
"tmuxline.vim
let g:tmuxline_preset = {
    \'a' : '#S',
    \'win'  : '#W',
    \'cwin'  : '#W',
    \'x' : '#(battery)',
    \'y' : '%l:%M',
    \'z' : '#h',
    \'options': {
        \'status-justify': 'left'}
    \}
let g:Tex_DefaultTargetFormat='pdf'
let g:Tex_Flavor='latex'
let g:Tex_ViewRule_pdf='mupdf'
let g:tsline_ensure_trailing_newlines = 1
let g:pencil#wrapModeDefault = 'hard'
let g:pencil#autoformat = 1
let g:pencil#conceallevel = 0
let g:airline#extensions#tabline#enabled = 0
let g:airline#extensions#whitespace#enabled = 1
let g:airline_powerline_fonts = 1
let g:bufferline_echo = 0
let g:ag_highlight=1
let g:used_javascript_libs = 'underscore, jquery, react'
let g:tmuxcomplete#trigger = 'omnifunc'
let g:ycm_semantic_triggers = {
    \ 'elm' : ['.'],
    \}
let g:ycm_path_to_python_interpreter = '/usr/bin/python'

augroup pencil
  autocmd!
  autocmd FileType markdown,mkd call pencil#init()
  autocmd FileType text         call pencil#init({'wrap': 'hard'})
  autocmd FileType tex          call pencil#init({'wrap': 'hard'})
augroup END

" mash caps to toggle insert mode
nnoremap <F12> i
inoremap <F12> <esc>l

" vimux
map <Leader>vrs :call VimuxRunCommand("clear; vdo rspec " . bufname("%"))<CR>
map <Leader>vrb :call VimuxRunCommand("clear; pry")<CR>


"""""""""""""""""""""""""""""""""""""""""""""""""""
"""Keybinds
"""""""""""""""""""""""""""""""""""""""""""""""""""
let hlstate=0 
nnoremap <F4> :if (hlstate == 0) \| nohlsearch \| else \| set hlsearch \| endif \| let hlstate=1-hlstate<cr>
nnoremap <Leader>ws :set list!<CR> 
imap <C-s> <esc>:w<cr> 
nnoremap <C-s> <esc>:w<cr>
nnoremap <Leader>w :w<cr>
map Q :qa<cr>
nnoremap <Leader>q :q<cr> 
nnoremap <Leader>sp :setlocal spell<cr>
nnoremap <Leader>lp :setlocal ft=python<cr>
nnoremap <Leader>md :setlocal ft=markdown<cr>
nnoremap <Leader>ed :ElmBrowseDocs<cr>
vmap <Leader>y "+y
vmap <Leader>d "+d
nmap <Leader>p "+p
nmap <Leader>P "+P
vmap <Leader>p "+p
vmap <Leader>P "+P
nnoremap <Leader>zz :let &scrolloff=999-&scrolloff<CR> 
nnoremap <Leader>cl :set cursorline!<CR> 
nnoremap <Leader>cc :set cursorcolumn!<CR> 
nnoremap <Leader>ln :set number!<cr>
nnoremap <Leader>rln :set relativenumber!<cr>
nnoremap <Leader>bl :buffers<cr> 
nnoremap <Leader>b1 :buffer1<cr> 
nnoremap <Leader>b2 :buffer2<cr> 
nnoremap <Leader>b3 :buffer3<cr> 
nnoremap <Leader>b4 :buffer4<cr> 
nnoremap <Leader>b5 :buffer5<cr> 
nnoremap <Leader>b6 :buffer6<cr> 
nnoremap <Leader>b7 :buffer7<cr> 
nnoremap <Leader>t  :enew<cr> 
nnoremap <Leader>bq :bd<cr> 
"create splits
nnoremap <C-o> :vsplit<cr>
nnoremap <C-u> :split<cr>
"window navigation
nnoremap <C-j> <C-W>j
nnoremap <C-k> <C-W>k
nnoremap <C-h> <C-W>h
nnoremap <C-l> <C-W>l
map / <Plug>(incsearch-forward)
map ? <Plug>(incsearch-backward)
map g/ <Plug>(incsearch-stay)
nnoremap <Leader>d :YcmCompleter GoToDefinition<cr>
nnoremap <Leader>p :CtrlPBufTag<cr>
nnoremap <Leader>o :CtrlPMRU<cr>
nnoremap <C-b> :CtrlPBuffer<cr>
nnoremap <C-f> :Ag 
let localleader = "\\"
nnoremap <silent> <Leader>tp :TogglePencil<cr>
nnoremap <Leader>rb :'<,'>s/pick/f/g<cr>
nnoremap <Leader>gb :Gblame<cr>
nnoremap <Leader>[ :tabprevious<cr>
nnoremap <Leader>] :tabnext<cr>
nnoremap <Leader>T :tabnew<cr>
